#!/bin/bash
set -eux
git_toplevel="$(git rev-parse --show-toplevel)"
pyrc="${git_toplevel}/pyproject.toml"
pythonpath="${git_toplevel}/usr/lib/python3/dist-packages"
export PYTHONPATH="${pythonpath}${PYTHONPATH+":${PYTHONPATH}"}"

pytest=(python3 -m pytest -o 'python_files=tests/*.py')
pytest_args=()
for arg in "$@"; do
  test_path="${pythonpath}/stdisplay/tests/${arg}.py"
  if [[ "${arg}" != -* && "${arg}" != */* && -f "${test_path}" ]]; then
    pytest_args+=("tests/${arg}.py")
  else
    pytest_args+=("${arg}")
  fi
done

if [[ ${#pytest_args[@]} -eq 0 ]]; then
  pytest_args=("${@}")
fi
black=(black --config="${pyrc}" --color --diff --check)
pylint=(pylint --rcfile="${pyrc}")
mypy=(mypy --config-file="${pyrc}")

cd "${pythonpath}/stdisplay/"
# Ideally, these variables should be ignored by the tests...
NO_COLOR="" COLORTERM="" TERM="xterm" "${pytest[@]}" "${pytest_args[@]}"
"${black[@]}" .
find . -type f -name "*.py" -print0 | xargs -0 "${pylint[@]}"
"${mypy[@]}" .

stdin_utils_to_stdout=(stcat stcatn)
stdin_utils_to_file=(sttee stsponge)
stdin_utils=("${stdin_utils_to_stdout[@]}" "${stdin_utils_to_file[@]}")
utils=(stprint stecho "${stdin_utils[@]}")
cd "${git_toplevel}/usr/bin"
"${black[@]}" -- "${utils[@]}"
"${pylint[@]}" -- "${utils[@]}"
for file in "${utils[@]}"; do
  "${mypy[@]}" -- "${file}"
done

for util in "${stdin_utils_to_stdout[@]}"; do
  ./"${util}" <&-
  ./"${util}" - <&-
done
for util in "${stdin_utils_to_file[@]}"; do
  ./"${util}" <&-
done

if ! [ -d "${HOME}/trojan-source" ]; then
  printf "%s\n" "WARNING: Not running unicode-testscript, ${HOME}/trojan-source does not exist.
To get it:

cd ~
git clone git@github.com:nickboucher/trojan-source.git" >&2
  exit 1
fi

cd "${git_toplevel}"
./unicode-testscript
